name: Build and Release to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install requirements
        run: python3 -m pip install -r ./requirements.txt

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Mkdocs build Project
        run: mkdocs build

      - name: Pull Vercel Environment Information
        working-directory: ./site
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./site
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./site
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
